name: tourism_app
description: "A new Flutter project."
# Prevents the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs to work.
dependencies:
  flutter:
    sdk: flutter
  # Adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: '^1.2.0+3' # or the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Recommended lints for good coding practices.
  flutter_lints: ^4.0.0

flutter:
  assets:
    # List of image assets
    - assets/london.jpg
    - assets/paris.jpg
    - assets/newyork.jpg
    - assets/img1.jpg
    - assets/img2.jpg
    - assets/img3.jpg
    - assets/img4.jpg
    - assets/img5.jpg
    - assets/img6.jpg
    - assets/img7.jpg
    - assets/img8.jpg
    - assets/img9.jpg
    - assets/img10.jpg
    - assets/img11.jpg
    - assets/img12.jpg
    - assets/img13.jpg
    - assets/img14.jpg
    - assets/img15.jpg
    - assets/img16.jpg
    - assets/logo.jpg

# Ensures that the Material Icons font is included with your application.
uses-material-design: true

# To add custom fonts to your application, add a fonts section here.
# Example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
